-- CreateTable
CREATE TABLE "Booking" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "hotel" TEXT NOT NULL,
    "lead_time" INTEGER NOT NULL,
    "arrival_date_year" INTEGER NOT NULL,
    "arrival_date_month" TEXT NOT NULL,
    "arrival_date_week_number" INTEGER NOT NULL,
    "arrival_date_day_of_month" INTEGER NOT NULL,
    "arrival_date" DATETIME NOT NULL,
    "stays_in_weekend_nights" INTEGER NOT NULL,
    "stays_in_week_nights" INTEGER NOT NULL,
    "adults" INTEGER NOT NULL,
    "children" INTEGER NOT NULL,
    "babies" INTEGER NOT NULL,
    "meal" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "market_segment" TEXT NOT NULL,
    "is_repeated_guest" BOOLEAN NOT NULL,
    "reserved_room_type" TEXT NOT NULL,
    "agent" TEXT,
    "company" TEXT,
    "customer_type" TEXT NOT NULL,
    "adr" REAL NOT NULL,
    "required_car_parking_spaces" INTEGER NOT NULL,
    "total_of_special_requests" INTEGER NOT NULL,
    "reservation_status" TEXT NOT NULL,
    "reservation_status_date" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "deleted_at" DATETIME
);
